import type { Topic, ConsumerGroup, Schema, User, Role, Permission, Cluster, Message } from './types';

export const mockClusters: Cluster[] = [
  { 
    id: 'dev-cluster', 
    name: 'Development Cluster', 
    bootstrapServers: 'localhost:9092', 
    status: 'DISCONNECTED', 
    nodeCount: 3,
    hasSchemaRegistry: true,
    hasKafkaConnect: true,
    schemaRegistryUrl: 'http://localhost:8081',
    kafkaConnectUrl: 'http://localhost:8083',
  },
  { 
    id: 'staging-cluster', 
    name: 'Staging Cluster', 
    bootstrapServers: 'staging-kafka:9092', 
    status: 'DISCONNECTED', 
    nodeCount: 3,
    hasSchemaRegistry: true,
    hasKafkaConnect: false,
    schemaRegistryUrl: 'http://staging-schema:8081',
  },
  { 
    id: 'prod-cluster', 
    name: 'Production Cluster', 
    bootstrapServers: 'prod-kafka:9092', 
    status: 'DISCONNECTED', 
    nodeCount: 5,
    hasSchemaRegistry: true,
    hasKafkaConnect: true,
    schemaRegistryUrl: 'http://prod-schema:8081',
    kafkaConnectUrl: 'http://prod-connect:8083',
  },
];

// Mock messages for different topics
export const mockMessages: Record<string, Message[]> = {
  'orders': [
    {
      partition: 0,
      offset: 1000,
      timestamp: '2026-05-17T10:30:00Z',
      timestampType: 'CREATE_TIME',
      key: 'order-12345',
      value: JSON.stringify({ orderId: 'order-12345', customerId: 'cust-001', amount: 299.99, status: 'PENDING', items: [{ productId: 'prod-001', quantity: 2, price: 149.99 }] }),
      headers: { 'correlation-id': 'corr-abc123', 'source': 'checkout-service' },
      keyFormat: 'STRING',
      valueFormat: 'JSON',
    },
    {
      partition: 1,
      offset: 998,
      timestamp: '2026-05-17T10:29:45Z',
      timestampType: 'CREATE_TIME',
      key: 'order-12344',
      value: JSON.stringify({ orderId: 'order-12344', customerId: 'cust-002', amount: 89.50, status: 'CONFIRMED', items: [{ productId: 'prod-003', quantity: 1, price: 89.50 }] }),
      headers: { 'correlation-id': 'corr-abc122', 'source': 'order-service' },
      keyFormat: 'STRING',
      valueFormat: 'JSON',
    },
    {
      partition: 2,
      offset: 1005,
      timestamp: '2026-05-17T10:29:30Z',
      timestampType: 'CREATE_TIME',
      key: 'order-12343',
      value: JSON.stringify({ orderId: 'order-12343', customerId: 'cust-003', amount: 450.00, status: 'SHIPPED', items: [{ productId: 'prod-002', quantity: 3, price: 150.00 }] }),
      headers: { 'correlation-id': 'corr-abc121', 'source': 'order-service' },
      keyFormat: 'STRING',
      valueFormat: 'JSON',
    },
    {
      partition: 0,
      offset: 999,
      timestamp: '2026-05-17T10:29:15Z',
      timestampType: 'CREATE_TIME',
      key: 'order-12342',
      value: JSON.stringify({ orderId: 'order-12342', customerId: 'cust-001', amount: 125.00, status: 'DELIVERED', items: [{ productId: 'prod-005', quantity: 5, price: 25.00 }] }),
      headers: { 'correlation-id': 'corr-abc120' },
      keyFormat: 'STRING',
      valueFormat: 'JSON',
    },
    {
      partition: 3,
      offset: 890,
      timestamp: '2026-05-17T10:29:00Z',
      timestampType: 'CREATE_TIME',
      key: 'order-12341',
      value: JSON.stringify({ orderId: 'order-12341', customerId: 'cust-004', amount: 75.25, status: 'CANCELLED', reason: 'Customer request' }),
      headers: { 'correlation-id': 'corr-abc119', 'source': 'checkout-service' },
      keyFormat: 'STRING',
      valueFormat: 'JSON',
    },
  ],
  'payments': [
    {
      partition: 0,
      offset: 500,
      timestamp: '2026-05-17T10:28:00Z',
      timestampType: 'CREATE_TIME',
      key: 'pay-9001',
      value: JSON.stringify({ paymentId: 'pay-9001', orderId: 'order-12344', amount: 89.50, method: 'CREDIT_CARD', status: 'SUCCESS', transactionId: 'txn-xyz789' }),
      headers: { 'correlation-id': 'corr-abc122' },
      keyFormat: 'STRING',
      valueFormat: 'JSON',
    },
    {
      partition: 1,
      offset: 499,
      timestamp: '2026-05-17T10:27:30Z',
      timestampType: 'CREATE_TIME',
      key: 'pay-9000',
      value: JSON.stringify({ paymentId: 'pay-9000', orderId: 'order-12343', amount: 450.00, method: 'PAYPAL', status: 'SUCCESS', transactionId: 'txn-xyz788' }),
      headers: { 'correlation-id': 'corr-abc121' },
      keyFormat: 'STRING',
      valueFormat: 'JSON',
    },
    {
      partition: 0,
      offset: 498,
      timestamp: '2026-05-17T10:27:00Z',
      timestampType: 'CREATE_TIME',
      key: 'pay-8999',
      value: JSON.stringify({ paymentId: 'pay-8999', orderId: 'order-12340', amount: 200.00, method: 'CREDIT_CARD', status: 'FAILED', error: 'Insufficient funds' }),
      headers: { 'correlation-id': 'corr-abc118' },
      keyFormat: 'STRING',
      valueFormat: 'JSON',
    },
  ],
  'notifications': [
    {
      partition: 0,
      offset: 2000,
      timestamp: '2026-05-17T10:30:05Z',
      timestampType: 'CREATE_TIME',
      key: 'notif-5001',
      value: JSON.stringify({ notificationId: 'notif-5001', userId: 'cust-001', type: 'ORDER_CREATED', channel: 'EMAIL', message: 'Your order #12345 has been placed successfully!' }),
      headers: { 'correlation-id': 'corr-abc123' },
      keyFormat: 'STRING',
      valueFormat: 'JSON',
    },
    {
      partition: 1,
      offset: 1999,
      timestamp: '2026-05-17T10:29:50Z',
      timestampType: 'CREATE_TIME',
      key: 'notif-5000',
      value: JSON.stringify({ notificationId: 'notif-5000', userId: 'cust-003', type: 'ORDER_SHIPPED', channel: 'SMS', message: 'Your order #12343 has been shipped!' }),
      headers: { 'correlation-id': 'corr-abc121' },
      keyFormat: 'STRING',
      valueFormat: 'JSON',
    },
  ],
  'user-events': [
    {
      partition: 0,
      offset: 10000,
      timestamp: '2026-05-17T10:25:00Z',
      timestampType: 'CREATE_TIME',
      key: 'cust-001',
      value: JSON.stringify({ userId: 'cust-001', event: 'LOGIN', ip: '192.168.1.100', userAgent: 'Mozilla/5.0', timestamp: '2026-05-17T10:25:00Z' }),
      headers: { 'session-id': 'sess-abc123' },
      keyFormat: 'STRING',
      valueFormat: 'JSON',
    },
    {
      partition: 2,
      offset: 9998,
      timestamp: '2026-05-17T10:24:30Z',
      timestampType: 'CREATE_TIME',
      key: 'cust-002',
      value: JSON.stringify({ userId: 'cust-002', event: 'PAGE_VIEW', page: '/products/prod-003', referrer: '/categories/electronics' }),
      headers: { 'session-id': 'sess-def456' },
      keyFormat: 'STRING',
      valueFormat: 'JSON',
    },
    {
      partition: 1,
      offset: 9999,
      timestamp: '2026-05-17T10:24:00Z',
      timestampType: 'CREATE_TIME',
      key: 'cust-003',
      value: JSON.stringify({ userId: 'cust-003', event: 'ADD_TO_CART', productId: 'prod-002', quantity: 3 }),
      headers: { 'session-id': 'sess-ghi789' },
      keyFormat: 'STRING',
      valueFormat: 'JSON',
    },
  ],
  'inventory': [
    {
      partition: 0,
      offset: 3000,
      timestamp: '2026-05-17T10:20:00Z',
      timestampType: 'CREATE_TIME',
      key: 'prod-001',
      value: JSON.stringify({ productId: 'prod-001', sku: 'SKU-001', name: 'Wireless Mouse', quantity: 150, warehouse: 'WH-01', lastUpdated: '2026-05-17T10:20:00Z' }),
      headers: {},
      keyFormat: 'STRING',
      valueFormat: 'JSON',
    },
    {
      partition: 1,
      offset: 2999,
      timestamp: '2026-05-17T10:19:30Z',
      timestampType: 'CREATE_TIME',
      key: 'prod-002',
      value: JSON.stringify({ productId: 'prod-002', sku: 'SKU-002', name: 'Mechanical Keyboard', quantity: 75, warehouse: 'WH-01', lastUpdated: '2026-05-17T10:19:30Z' }),
      headers: {},
      keyFormat: 'STRING',
      valueFormat: 'JSON',
    },
  ],
  'shipping': [
    {
      partition: 0,
      offset: 1500,
      timestamp: '2026-05-17T10:15:00Z',
      timestampType: 'CREATE_TIME',
      key: 'ship-7001',
      value: JSON.stringify({ shipmentId: 'ship-7001', orderId: 'order-12343', carrier: 'FedEx', trackingNumber: 'FX123456789', status: 'IN_TRANSIT', estimatedDelivery: '2026-05-19' }),
      headers: { 'correlation-id': 'corr-abc121' },
      keyFormat: 'STRING',
      valueFormat: 'JSON',
    },
  ],
  'analytics': [
    {
      partition: 0,
      offset: 50000,
      timestamp: '2026-05-17T10:30:00Z',
      timestampType: 'CREATE_TIME',
      key: null,
      value: JSON.stringify({ metric: 'page_views', value: 1523, period: '1h', timestamp: '2026-05-17T10:00:00Z' }),
      headers: { 'aggregation': 'hourly' },
      keyFormat: 'STRING',
      valueFormat: 'JSON',
    },
    {
      partition: 1,
      offset: 49999,
      timestamp: '2026-05-17T10:30:00Z',
      timestampType: 'CREATE_TIME',
      key: null,
      value: JSON.stringify({ metric: 'orders_count', value: 87, period: '1h', timestamp: '2026-05-17T10:00:00Z' }),
      headers: { 'aggregation': 'hourly' },
      keyFormat: 'STRING',
      valueFormat: 'JSON',
    },
    {
      partition: 2,
      offset: 49998,
      timestamp: '2026-05-17T10:30:00Z',
      timestampType: 'CREATE_TIME',
      key: null,
      value: JSON.stringify({ metric: 'revenue', value: 12450.75, currency: 'USD', period: '1h', timestamp: '2026-05-17T10:00:00Z' }),
      headers: { 'aggregation': 'hourly' },
      keyFormat: 'STRING',
      valueFormat: 'JSON',
    },
  ],
};

export const mockTopics: Topic[] = [
  { name: 'orders', partitionCount: 6, replicationFactor: 3, internal: false, messageCount: 125000 },
  { name: 'payments', partitionCount: 3, replicationFactor: 3, internal: false, messageCount: 89000 },
  { name: 'notifications', partitionCount: 4, replicationFactor: 3, internal: false, messageCount: 45000 },
  { name: 'user-events', partitionCount: 8, replicationFactor: 3, internal: false, messageCount: 234000 },
  { name: 'inventory', partitionCount: 4, replicationFactor: 3, internal: false, messageCount: 67000 },
  { name: 'shipping', partitionCount: 3, replicationFactor: 3, internal: false, messageCount: 34000 },
  { name: 'analytics', partitionCount: 12, replicationFactor: 3, internal: false, messageCount: 890000 },
  { name: '__consumer_offsets', partitionCount: 50, replicationFactor: 3, internal: true, messageCount: 15000 },
  { name: '__transaction_state', partitionCount: 50, replicationFactor: 3, internal: true, messageCount: 500 },
];

export const mockConsumerGroups: ConsumerGroup[] = [
  { groupId: 'order-processor', state: 'STABLE', members: 3, topics: ['orders'], totalLag: 1250 },
  { groupId: 'payment-handler', state: 'STABLE', members: 2, topics: ['payments'], totalLag: 0 },
  { groupId: 'notification-sender', state: 'STABLE', members: 2, topics: ['notifications'], totalLag: 45 },
  { groupId: 'analytics-consumer', state: 'STABLE', members: 4, topics: ['analytics', 'user-events'], totalLag: 8900 },
  { groupId: 'inventory-sync', state: 'EMPTY', members: 0, topics: ['inventory'], totalLag: 2300 },
  { groupId: 'shipping-tracker', state: 'STABLE', members: 1, topics: ['shipping'], totalLag: 120 },
];

export const mockSchemas: Schema[] = [
  { subject: 'orders-value', version: 3, id: 1, schemaType: 'AVRO', schema: '{"type":"record","name":"Order","fields":[{"name":"id","type":"string"},{"name":"amount","type":"double"}]}', compatibility: 'BACKWARD' },
  { subject: 'payments-value', version: 2, id: 2, schemaType: 'AVRO', schema: '{"type":"record","name":"Payment","fields":[{"name":"orderId","type":"string"},{"name":"status","type":"string"}]}', compatibility: 'BACKWARD' },
  { subject: 'user-events-value', version: 5, id: 3, schemaType: 'JSON', schema: '{"type":"object","properties":{"userId":{"type":"string"},"event":{"type":"string"}}}', compatibility: 'FORWARD' },
  { subject: 'notifications-value', version: 1, id: 4, schemaType: 'AVRO', schema: '{"type":"record","name":"Notification","fields":[{"name":"userId","type":"string"},{"name":"message","type":"string"}]}', compatibility: 'FULL' },
];

export const mockUsers: User[] = [
  { id: 1, username: 'admin', email: 'admin@example.com', fullName: 'System Admin', isAdmin: true, isActive: true, roles: ['ADMIN'], createdAt: '2024-01-01T00:00:00Z', updatedAt: '2024-01-01T00:00:00Z' },
  { id: 2, username: 'developer', email: 'dev@example.com', fullName: 'John Developer', isAdmin: false, isActive: true, roles: ['DEVELOPER'], createdAt: '2024-01-15T00:00:00Z', updatedAt: '2024-01-15T00:00:00Z' },
  { id: 3, username: 'viewer', email: 'viewer@example.com', fullName: 'Jane Viewer', isAdmin: false, isActive: true, roles: ['VIEWER'], createdAt: '2024-02-01T00:00:00Z', updatedAt: '2024-02-01T00:00:00Z' },
];

export const mockRoles: Role[] = [
  { id: 1, name: 'ADMIN', description: 'Full system access', isSystem: true, permissions: [], createdAt: '2024-01-01T00:00:00Z', updatedAt: '2024-01-01T00:00:00Z' },
  { id: 2, name: 'DEVELOPER', description: 'Can manage topics and consumer groups', isSystem: false, permissions: [], createdAt: '2024-01-01T00:00:00Z', updatedAt: '2024-01-01T00:00:00Z' },
  { id: 3, name: 'VIEWER', description: 'Read-only access', isSystem: false, permissions: [], createdAt: '2024-01-01T00:00:00Z', updatedAt: '2024-01-01T00:00:00Z' },
];

export const mockPermissions: Permission[] = [
  { id: 1, resource: 'TOPIC', action: 'READ', resourcePattern: '*', clusterIds: ['dev-cluster'], description: 'Read all topics', createdAt: '2024-01-01T00:00:00Z' },
  { id: 2, resource: 'TOPIC', action: 'WRITE', resourcePattern: '*', clusterIds: ['dev-cluster'], description: 'Write to all topics', createdAt: '2024-01-01T00:00:00Z' },
  { id: 3, resource: 'CONSUMER_GROUP', action: 'READ', resourcePattern: '*', clusterIds: ['dev-cluster'], description: 'Read all consumer groups', createdAt: '2024-01-01T00:00:00Z' },
];
